
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "my-chart.fullname" . }}
  namespace: default
spec:
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app:  {{ include "my-chart.fullname" . }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}